import { test } from 'vitest';
import assert from 'node:assert/strict';
import { SCHEMA_VERSION, stableId, sha256, canonicalJson, parseDocument, serializeDocument, validateDocument, validateMigrationConfig } from '../../src/contracts/index.js';
import type { RunReport } from '../../src/contracts/index.js';

const snapshot = { schemaVersion: SCHEMA_VERSION, id:'api_fixture', openapi:'3.1.0', digest:sha256('{}'), documents:[{file:'api.json',digest:sha256('{}')}],operations:[],references:[],diagnostics:[] };
const fixture:RunReport={schemaVersion:SCHEMA_VERSION,id:'run_fixture',inputs:{old:{file:'old.json',digest:snapshot.digest},new:{file:'new.json',digest:snapshot.digest}},snapshots:{old:snapshot,new:snapshot},changes:[],uses:[],findings:[],repairs:[],verification:[{id:'check_fixture',level:5,status:'skipped',properties:[],evidence:[],durationMs:0,environment:{node:process.version},reason:'No command authorization supplied'}],limitations:['Synthetic serialization fixture, no analysis performed'],diagnostics:[]};
test('complete report serialization fixture preserves skipped verification',()=>{assert.deepEqual(parseDocument('RunReport',serializeDocument('RunReport',fixture)),fixture);assert.equal(fixture.verification[0]?.status,'skipped');});
test('stable IDs ignore object key insertion order and preserve array order',()=>{assert.equal(stableId('x',{a:1,b:2}),stableId('x',{b:2,a:1}));assert.notEqual(stableId('x',[1,2]),stableId('x',[2,1]));assert.throws(()=>canonicalJson({x:undefined}));assert.throws(()=>canonicalJson(NaN));});
test('rejects unsupported version, nested malformed values and unknown properties',()=>{assert.throws(()=>validateDocument('RunReport',{...fixture,schemaVersion:'2.0'}),/schemaVersion/);assert.throws(()=>validateDocument('RunReport',{...fixture,verification:[{...fixture.verification[0],status:'success'}]}),/status/);assert.throws(()=>validateDocument('ApiSnapshot',{...snapshot,operations:[{}]}),/required/);assert.throws(()=>validateDocument('RunReport',{...fixture,extra:true}),/unknown property/);});
test('migration rejects duplicate decisions and non-origin URLs',()=>{const m={schemaVersion:SCHEMA_VERSION,allowedOrigins:['http://localhost:1234'],operations:[],renames:[],values:[]};assert.deepEqual(validateMigrationConfig(m),m);assert.throws(()=>validateMigrationConfig({...m,operations:[{from:'a',to:'b'},{from:'a',to:'c'}]}),/duplicate/);assert.throws(()=>validateMigrationConfig({...m,allowedOrigins:['https://example.com/path']}),/origin/);});
test('plan rejects traversal, overlapping edits and separate status confusion',()=>{const p={schemaVersion:SCHEMA_VERSION,id:'p',reportId:'r',migration:{schemaVersion:SCHEMA_VERSION,allowedOrigins:[],operations:[],renames:[],values:[]},applicationStatus:'proposed',files:[],resolvedFindingIds:[],partialFindingIds:[],pendingFindingIds:[],unifiedDiff:'',explanations:[],diagnostics:[]};validateDocument('RepairPlan',p);assert.throws(()=>validateDocument('RepairPlan',{...p,applicationStatus:'passed'}));assert.throws(()=>validateDocument('RepairPlan',{...p,files:[{file:'../escape.ts',originalHash:sha256(''),edits:[]}]}));const edit={start:0,end:2,oldText:'ab',newText:'cd',findingIds:[],reason:'explicit'};assert.throws(()=>validateDocument('RepairPlan',{...p,files:[{file:'safe.ts',originalHash:sha256('abc'),edits:[edit,{...edit,start:1,end:3}]}]}),/overlapping/);});
test('migration accepts nested parent paths only for body locations',()=>{const m={schemaVersion:SCHEMA_VERSION,allowedOrigins:[],operations:[],renames:[{operationId:'o',location:'request',from:'city',to:'town',parent:['address']}],values:[{operationId:'o',location:'request',name:'country',value:'ES',parent:['address']}]};assert.deepEqual(validateMigrationConfig(m),m);assert.doesNotThrow(()=>validateMigrationConfig({...m,renames:[...m.renames,{operationId:'o',location:'request',from:'city',to:'town'}]}));assert.throws(()=>validateMigrationConfig({...m,renames:[...m.renames,{...m.renames[0]}]}),/duplicate/);assert.throws(()=>validateMigrationConfig({...m,renames:[{operationId:'o',location:'query',from:'a',to:'b',parent:['x']}]}),/query/);assert.throws(()=>validateMigrationConfig({...m,values:[{...m.values[0],parent:['']}]}),/non-empty/);});
test('consumer use accepts an optional wrapper reference with a safe relative file',()=>{const use={id:'u',file:'src/a.ts',fileHash:sha256('a'),range:{start:0,end:1,line:1,column:1},client:'fetch',urlExpression:'x',operationIds:[],bindings:[],resolution:'resolved',confidence:'medium',reason:'r',via:{name:'api',file:'src/http.ts',range:{start:0,end:3,line:1,column:1}}};const scan={schemaVersion:SCHEMA_VERSION,uses:[use],findings:[],diagnostics:[],limitations:[]};validateDocument('ScanResult',scan);assert.throws(()=>validateDocument('ScanResult',{...scan,uses:[{...use,via:{...use.via,file:'../x.ts'}}]}),/relative/);});
